#!/usr/bin/env python3
import os
import sys
import asyncio
import json
import random
import re
import shutil
from urllib.parse import urlparse
from functools import lru_cache
from typing import List, Dict, Union, Tuple, Optional
import aiofiles
import aiohttp
import pyrogram
from pyrogram.handlers import MessageHandler
from pyrogram.filters import command
from pyrogram.types import Message, InlineKeyboardButton, InlineKeyboardMarkup, CallbackQuery
from pyrogram.errors import FloodWait, UserIsBlocked, MessageNotModified, MessageEmpty, MessageIdInvalid, ChatAdminRequired
from cloudscraper import create_scraper
from gdown import download as gdown_download
from gdown import GDriveFileTransferError
from gdown.download import DownloadError
from gdown.gdrive import GDriveFile
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable
from gdown.service import ServiceException
from gdown.service import ServiceUnavailable

