from bot import CMD_SUFFIX
from os import environ

def get_command(name: str, default: str):
    return environ.get(name, default)

commands = {
    'StartCommand': get_command(f'START_COMMAND', f'start{CMD_SUFFIX}'),
    'MirrorCommand': get_command(f'MIRROR_COMMAND', f'mirror{CMD_SUFFIX}'),
    'UnzipMirrorCommand': get_command(f'UNZIP_COMMAND', f'unzipmirror{CMD_SUFFIX}'),
    'ZipMirrorCommand': get_command(f'ZIP_COMMAND', f'zipmirror{CMD_SUFFIX}'),
    'LeechCommand': get_command(f'LEECH_COMMAND', f'leech{CMD_SUFFIX}'),
    'UnzipLeechCommand': get_command(f'UNZIPLEECH_COMMAND', f'unzipleech{CMD_SUFFIX}'),
    'ZipLeechCommand': get_command(f'ZIPLEECH_COMMAND', f'zipleech{CMD_SUFFIX}'),
    'CloneCommand': get_command(f'CLONE_COMMAND', f'clone{CMD_SUFFIX}'),
    'QbMirrorCommand': get_command(f'QBMIRROR_COMMAND', f'qbmirror{CMD_SUFFIX}'),
    'QbUnzipMirrorCommand': get_command(f'QBUNZIP_COMMAND', f'qbunzipmirror{CMD_SUFFIX}'),
    'QbZipMirrorCommand': get_command(f'QBZIP_COMMAND', f'qbzipmirror{CMD_SUFFIX}'),
    'QbLeechCommand': get_command(f'QBLEECH_COMMAND', f'qbleech{CMD_SUFFIX}'),
    'QbUnzipLeechCommand': get_command(f'QBZIPLEECH_COMMAND', f'qbunzipleech{CMD_SUFFIX}'),
    'QbZipLeechCommand': get_command(f'QBUNZIPLEECH_COMMAND', f'qbzipleech{CMD_SUFFIX}'),
    'ScrapeCommand': get_command(f'SCRAPE_COMMAND', f'scrape{CMD_SUFFIX}'),
    'YtdlCommand': get_command(f'YTDL_COMMAND', f'ytdl{CMD_SUFFIX}'),
    'YtdlZipCommand': get_command(f'YTDLZIP_COMMAND', f'ytdlzip{CMD_SUFFIX}'),
    'YtdlLeechCommand': get_command(f'YTDLLEECH_COMMAND', f'ytdlleech{CMD_SUFFIX}'),
    'YtdlZipLeechCommand': get_command(f'YTDLZIPLEECH_COMMAND', f'ytdlzipleech{CMD_SUFFIX}'),
    'MediaInfoCommand': get_command(f'MEDIAINFO_COMMAND', f'mediainfo{CMD_SUFFIX}'),
    'UserSetCommand': get_command(f'USERSET_COMMAND', f'usetting{CMD_SUFFIX}'),
    'BotSetCommand': get_command(f'BOT_SETTING', f'bsetting{CMD_SUFFIX}'),
    'CancelMirror': get_command(f'CANCEL_COMMAND', f'cancel{CMD_SUFFIX}'),
    'CancelAllCommand': get_command(f'CANCEL_ALL_COMMAND', f'cancelall{CMD_SUFFIX}'),
    'ListCommand': get_command(f'LIST_COMMAND', f'list{CMD_SUFFIX}'),
    'SearchCommand': get_command(f'SEARCH_COMMAND', f'search{CMD_SUFFIX}'),
    'StatusCommand': get_command(f'STATUS_COMMAND', f'status{CMD_SUFFIX}'),
    'UsersCommand': get_command(f'USERS_COMMAND', f'users{CMD_SUFFIX}'),
    'PaidUsersCommand': get_command(f'PAID_COMMAND', f'paid{CMD_SUFFIX}'),
    'AddPaidCommand': get_command(f'ADDPAID_COMMAND', f'addpaid{CMD_SUFFIX}'),
    'RmPaidCommand': get_command(f'RMPAID_COMMAND', f'rmpaid{CMD_SUFFIX}'),
    'AuthorizeCommand': get_command(f'AUTH_COMMAND', f'authorize{CMD_SUFFIX}'),
    'UnAuthorizeCommand': get_command(f'UNAUTH_COMMAND', f'unauthorize{CMD_SUFFIX}'),
    'AddSudoCommand': get_command(f'ADDSUDO_COMMAND', f'addsudo{CMD_SUFFIX}'),
    'RmSudoCommand': get_command(f'RMSUDO_COMMAND', f'rmsudo{CMD_SUFFIX}'),
    'PingCommand': get_command(f'PING_COMMAND', f'ping{CMD_SUFFIX}'),
    'RestartCommand': get_command(f'RESTART_COMMAND', f'restart{CMD_SUFFIX}'),
    'StatsCommand': get_command(f'STATS_COMMAND', f'stats{CMD_SUFFIX}'),
    'HelpCommand': get_command(f'HELP_COMMAND', f'help{CMD_SUFFIX}'),
    'LogCommand': get_command(f'LOG_COMMAND', f'log{CMD_SUFFIX}'),
    'BtSelectCommand': get_command(f'BTSEL_COMMAND', f'btsel{CMD_SUFFIX}'),
    'SpeedCommand': get_command(f'SPEEDTEST_COMMAND', f'speedtest{CMD_SUFFIX}'),
    'CountCommand': get_command(f'COUNT_COMMAND', f'count{CMD_SUFFIX}'),
    'DeleteCommand': get_command(f'DELETE_COMMAND', f'del{CMD_SUFFIX}'),
    'ShellCommand': get_command(f'SHELL_COMMAND', f'shell{CMD_SUFFIX}'),
    'ExecHelpCommand': get_command(f'EXEHELP_COMMAND', f'exechelp{CMD_SUFFIX}'),
    'HashCommand': get_command(f'HASH_COMMAND', f'hash{CMD_SUFFIX}'),
    'RssListCommand': get_command(f'RSSLIST_COMMAND', f'rsslist{CMD_SUFFIX}'),
    'RssGetCommand': get_command(f'RSSGET_COMMAND', f'rssget{CMD_SUFFIX}'),
    'RssSubCommand': get_command(f'RSSSUB_COMMAND', f'rsssub{CMD_SUFFIX}'),
    'RssUnSubCommand': get_command(f'RSSUNSUB_COMMAND', f'rssunsub{CMD_SUFFIX}'),
    'RssSettingsCommand': get_command(f'RSSSET_COMMAND', f'rssset{CMD_SUFFIX}'),
    'WayBackCommand': get_command(f'WAYBACK_COMMAND', f'wayback{CMD_SUFFIX}'),
    'AddleechlogCommand': get_command(f'ADDLEECHLOG_CMD', f'addleechlog{CMD_SUFFIX}'),
    'RmleechlogCommand': get_command(f'RMLEECHLOG_CMD', f'rmleechlog{CMD_SUFFIX}'),
    'SelectCategory': f'catsel{CMD_SUFFIX}',
    'EvalCommand': f'eval{CMD_SUFFIX}',
    'ExecCommand': f'exec{CMD_SUFFIX}',
    'ClearLocalsCommand': f'clearlocals{CMD_SUFFIX}',
    'LimitCommand': get_command(f'LIMIT_COMMAND', f'limit{CMD_SUFFIX}'),
    'DriveCleanCommand': get_command(f'DRIVECLEAN_COMMAND', f'driveclean{CMD_SUFFIX}'),
}

BotCommands = type('_BotCommands', (object,), commands)()
